AllCops:
  Include:
    - 'app'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/test_helper.rb'

Metrics/LineLength:
  Enabled: false